### ISSUE TITLE
VRDP is not available when VM ran from this service.

### ISSUE THREAD

**Issue by vipinjn24** [onlyfang/VBoxVmService#1]
Hi,

I ran the VM from the service and i can see that i was not able to connect it through VRDP.

This is not the case when i ran the VM using headless from the app.

Please resolve.

**Comment by richard-scott** [comment]
Change the user account that the service runs under to be your own account that you want to use the Dekstop GUI with. Then you can use both the service and the GUI to access/start/stop VM's

**Comment by vipinjn24** [comment]
@richard-scott nopes its not working as it starts another vboxsvc to interact with and whatever changes you do in the oracle side they will be discarded when you shutdown the service.

Please close this issue, i got to know on how to enable the rdp for the vm. It was not an issue at all.
