### ISSUE TITLE
6.0-Pumpkin / Service won't start

### ISSUE THREAD

**Issue by GustelDE** [onlyfang/VBoxVmService#11]
Hi,

installed VirtualBox 6.0.2 and VBoxVmService version 6.0. The VBoxVmService won't start under win server 2012r2. The error reads "StartServiceCtrlDispatcher - Der Dienstprozess konnte keine Verbindung mit dem Dienstcontroller herstellen" (my english translation: StartServiceCtrlDispatcher - The service-process was unable to connect to the service-controller).

The installer terminates as well with an error (MSVCR120.dll not found). Had to install the "Visual C++ Redistributable Packages for Visual Studio 2013" x86 version. Then the installtion finishes but the service won't start. Tried several reboots, and "run as administrator" -> no effect.

Downgraded to 5.2 - everything works fine.

Thanks

**Comment by GustelDE** [comment]
Is there a solution for this problem?

**Comment by eneerge** [comment]
I just had this same issue but solved it by also installing the x64 version of the "Visual C++ Redistributable Packages for Visual Studio 2013" package.

I installed the x86 and then x64 version respectively.

**Comment by GustelDE** [comment]
Thanks, but no success. Installed both x86 and x64 versions in germand and after deinstallation in english. Starting the service will always gernerate an error 1053.

The only way I got it work was deleting the "VBoxVmService64.exe" and renaming the VBoxVmService.exe to VBoxVmService64.exe. I think this is the 32 Bit version?

But in my opinion this is an ugly solution!
After 2 month still no response from the programming team? :(

**Comment by onlyfang** [comment]
The dependency issue must has been introduced by my recent change on CMake. I'll see if it's possible to static link to runtime library to avoid the trouble.  But I am not sure if this is your case. I am confused why it can be fixed by renaming exe.

**Comment by GustelDE** [comment]
The 5.2 64Bit version and the 6.0 32Bit version work.
Only the 6.0 64Bit versions stucks with an Error 1053 (if I try to start the service manually via the services mmc).

**Comment by cagivacode** [comment]
I was in the same boat....just got rid of my last 32bit VM and moved to VBox 6.X. So I went to 6.0 pumpkin.
With same issue as OP on win 10.
The 32bit Pumpkin service runs the 64bit Pumpkin refuses to start (Error 1053)

**Comment by cirrus-wizard** [comment]
> I just had this same issue but solved it by also installing the x64 version of the "Visual C++ Redistributable Packages for Visual Studio 2013" package.
> 
> I installed the x86 and then x64 version respectively.

Thanks, @eneerge.  Installing that x64 version worked for me.

**Comment by indigca** [comment]
Also Running OK on Windows Server 2016 after installing x64 version of the Visual C++ Redistributable Package for Visual Studio 2013"

**Comment by Orionn2000** [comment]
Win10 x64 here, and I'm still getting the error about msvcr120.dll. I've installed the "Visual C++ Redistributable Package for Visual Studio 2013", rebooted a few times, tried installing the dll from alternative sources. Still getting the error, when I try to run the tray tool too.

**Comment by Chanix** [comment]
I'm in the same boat but solved?

Win10 Pro Workstation 64bit 10.0.17134
pumpkin + virtualbox 6.0.8

First, told me msvcr120.dll not found.
After installing "x64 version of the Visual C++ Redistributable Package for Visual Studio 2013",  not work.
BUT after installing "x86 version of the Visual C++ Redistributable Package for Visual Studio 2013",   IT WORKED.

I am confused with 32 or 64...anyway, it worked :)

**Comment by rogersmj** [comment]
I had the same results as @Chanix . Despite having an x64 system, I couldn't get it to work until I installed the x86 versions of the C++ Redist for VS 2013 package.

**Comment by Per9** [comment]
Same problem for me. I noticed the static fix so I had even tried installing VS 2013 x64, VS 2019 x86 and x64 and had given up. Then I finally found this issue and installed VS 2013 x86 which fixed it. I think you should do a new release with the fix.
