### ISSUE TITLE
Cannot start service with VirtualBox 5.2.30

### ISSUE THREAD

**Issue by jackmaninov** [onlyfang/VBoxVmService#18]
I'm having trouble starting the service. Each time it fails immediately with:

Error creating VirtualBox instance! rc = 0x80004002

This is on:
Windows 10 version 1903
VirtualBox 5.2.30 r130521
VBoxVMService 6

Any ideas? I have already confirmed my VBOX_USER_HOME is correct. Thank you.

**Comment by onlyfang** [comment]
VBoxVMService and VirtualBox versions need to match. Check https://github.com/onlyfang/VBoxVmService/wiki.
