### ISSUE TITLE
VBoxVmService shows VM as started (Stop option only), but in the VirtualBox GUI they are NOT started...

### ISSUE THREAD

**Issue by martijintro** [onlyfang/VBoxVmService#23]
VBoxVmService shows VM as started (Stop option only), but in the VirtualBox GUI they are NOT started... why?

**Comment by coppsi** [comment]
Yes i have seen too, the startet VM by VboxmService is not controlled to see in the VirtualBox manager after starting VirtualBox.

**Comment by onlyfang** [comment]
Right, as explained in https://github.com/onlyfang/VBoxVmService/wiki/Runing-VirtualBox-GUI-together-with-VBoxVmService, VBoxVmService status is not shared with VirtualBox GUI.
