### ISSUE TITLE
Antivirus-Alert when Downloading version 6

### ISSUE THREAD

**Issue by HoffmannTom** [onlyfang/VBoxVmService#25]
Hello,
our GData-Antivirus prevents downloading the exe-file.
An analysis on virustotal shows some alerts:
https://www.virustotal.com/gui/file/24cc6dcf0c5f8c25fca5181952e86c5525d83f981caece6c5de1f3e1ec673546/detection

It says that it contains probably unwanted software.
Could you check why this alert is triggered?
Is there some unwanted software installed?

Greetings, Thomas

**Comment by onlyfang** [comment]
I believe this is false alarm. As long as you download from https://github.com/onlyfang/VBoxVmService/releases you should be safe. 
You can also compile the binary on your own, just need to install Visual Studio Community 2019, CMake, and Inno Setup.
