### ISSUE TITLE
asking handling organisation 

### ISSUE THREAD

**Issue by coppsi** [onlyfang/VBoxVmService#26]
Your example
Vm1]
VmName=winxp                                                As you can see, the above values almost repeat for every [VmX] section of the file.
ShutdownMethod=acpipowerbutton
AutoStart=no                                                This VM will not be started automatically.

My question is ,

for what is this good Vm1)    Autostart=no
how can i start the WinXP VM and how can i  shutdown the winxp VM

And when is must start manually, why it is in the ini written ?

Your example
[Vm0]
VmName=ubuntu                                               The name of the VM to start (case sensitive!)
ShutdownMethod=savestate                                    The shutdown method ("savestate", or "acpipowerbutton"). When "savestate" is used, the machine state is saved and will be resumed when you start VM next time. When "acpipowerbutton" is used, as long as client OS support it, the VM will get a clean shutdown. If your VM takes long time to poweroff, it's recommanded to use savestate, which could be done very quickly.
AutoStart=yes                                               Whether or not this VM will be started automatically, when VBoxVmService runs. Default to "yes".

My QUestion is:
Yes it runs . i have modifed for me.
But how is the VM to shutdown, when no user is working by RDP with this Normaly I open the VM in virtualBox self, and after starting and using I go inside of the VM art the Point to shutdown as i do it in normal wondows PC

Genral ask:
By your methode , when I open the VirtualBox over my windows PC , there is not standing "running" at the automaticaly started VM by your Service.

**Comment by onlyfang** [comment]
For your questions:
1) You can start/stop individual VM from VmServiceTray.
2) You can still poweroff the VM from within the OS. 
Hope that helps.
