### ISSUE TITLE
Service fails to respond in a timely fashion

### ISSUE THREAD

**Issue by pipingpiper** [onlyfang/VBoxVmService#32]
Hi there, having issues with the 6.0 version not starting. The error message I get when using windows CLI to start the service is:

C:\Windows\system32>C:\vms\VmServiceControl.exe -s
StartService failed: The service did not respond to the start or control request in a timely fashion.

Running it from the tray doesn't do...anything. No errors or VMs starting, just nothing. It does not create any .log files, as the service doesn't start. Downgrading to 5.2 the service starts, but isn't compatible with virtualbox 6.0. The VM starts fine from virtualbox and I've tried restarting/installing/uninstalling several times. Also already install x86 version of VC++ 2013 so that the service wasn't missing dependencies. The account is in the admin group. I can't think of anything else to troubleshoot. 

contents of the .ini file are below:

`[Settings]
VBOX_USER_HOME=C:\Users\pipin\.VirtualBox
RunWebService=no
PauseShutdown=5000

[Vm0]
VmName=HomeAssistant
ShutdownMethod=savestate
AutoStart=yes
`

**Comment by andyacer** [comment]
I had the same problem.  What solved it for me was installing "Visual C++ Redistributable Packages for Visual Studio 2013."  It worked immediately.  Here's a link to that download:

https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by pipingpiper** [comment]
Reinstalled C++ redistributable and then reinstalled VBoxVMService fixed the issue for me. 

Thanks!
