### ISSUE TITLE
6.1

### ISSUE THREAD

**Issue by firelook** [onlyfang/VBoxVmService#33]
it seems it doesn't work with 6.1 : can not launch the service

**Comment by informaticapb** [comment]
I can confirm that. I attached the log, but it doesn't show much.
`12/12/2019, 06:59:34 - Received system shutdown event.
12/12/2019, 06:59:51 - Received service shutdown event.
12/12/2019, 07:01:04 -   VM VPN has being shutted down.
12/12/2019, 07:01:10 - VBoxVmService stopped.
12/12/2019, 07:30:19 - C:\vms\VBoxVmService64.exe
12/12/2019, 07:30:20 - C:\vms\VBoxVmService.ini
12/12/2019, 07:30:20 - C:\vms\VBoxVmService.log
12/12/2019, 07:30:20 - VBoxVmService started.
12/12/2019, 07:31:12 - List all the VMs found by VBoxVmService
12/12/2019, 07:31:12 -   VM0: VPN is saved.
12/12/2019, 07:32:05 -   VM VPN has been started up.
12/12/2019, 23:05:11 - Received system shutdown event.
12/12/2019, 23:05:17 - Received service shutdown event.
12/12/2019, 23:06:08 -   VM VPN has being shutted down.
12/12/2019, 23:06:15 - VBoxVmService stopped.
12/12/2019, 23:12:27 - C:\vms\VBoxVmService64.exe
12/12/2019, 23:12:27 - C:\vms\VBoxVmService.ini
12/12/2019, 23:12:27 - C:\vms\VBoxVmService.log
12/12/2019, 23:12:27 - VBoxVmService started.
12/12/2019, 23:14:12 - List all the VMs found by VBoxVmService
12/12/2019, 23:14:12 -   VM0: VPN is saved.
12/12/2019, 23:15:16 -   VM VPN has been started up.
12/13/2019, 05:48:02 - Received system shutdown event.
12/13/2019, 05:48:13 - Received service shutdown event.
12/13/2019, 05:48:41 -   VM VPN has being shutted down.
12/13/2019, 05:48:46 - VBoxVmService stopped.
12/13/2019, 06:51:16 - C:\vms\VBoxVmService64.exe
12/13/2019, 06:51:16 - C:\vms\VBoxVmService.ini
12/13/2019, 06:51:16 - C:\vms\VBoxVmService.log
12/13/2019, 06:51:16 - VBoxVmService started.
12/13/2019, 06:52:17 - List all the VMs found by VBoxVmService
12/13/2019, 08:00:16 - C:\vms\VBoxVmService64.exe
12/13/2019, 08:00:16 - C:\vms\VBoxVmService.ini
12/13/2019, 08:00:16 - C:\vms\VBoxVmService.log
12/13/2019, 08:00:16 - VBoxVmService started.
12/13/2019, 08:00:26 - List all the VMs found by VBoxVmService
12/13/2019, 08:00:43 - C:\vms\VBoxVmService64.exe
12/13/2019, 08:00:43 - C:\vms\VBoxVmService.ini
12/13/2019, 08:00:43 - C:\vms\VBoxVmService.log
12/13/2019, 08:00:43 - VBoxVmService started.
12/13/2019, 08:00:43 - List all the VMs found by VBoxVmService
12/13/2019, 08:00:54 - C:\vms\VBoxVmService64.exe
12/13/2019, 08:00:54 - C:\vms\VBoxVmService.ini
12/13/2019, 08:00:54 - C:\vms\VBoxVmService.log
12/13/2019, 08:00:54 - VBoxVmService started.
12/13/2019, 08:00:54 - List all the VMs found by VBoxVmService
12/13/2019, 08:01:20 - C:\vms\VBoxVmService64.exe
12/13/2019, 08:01:20 - C:\vms\VBoxVmService.ini
12/13/2019, 08:01:20 - C:\vms\VBoxVmService.log
12/13/2019, 08:01:20 - VBoxVmService started.
12/13/2019, 08:01:20 - List all the VMs found by VBoxVmService
`

**Comment by heintron** [comment]
Well, this explains why I cannot get it running :(

**Comment by onlyfang** [comment]
Fixed in https://github.com/onlyfang/VBoxVmService/releases/tag/6.1-Kiwi.
