### ISSUE TITLE
 VBoxVmService-6.1-Kiwi.exe is detected by antivirus programs

### ISSUE THREAD

**Issue by hom-mp** [onlyfang/VBoxVmService#37]
Hi there,

the Virus-total check returns that 5 Antivirus-scanners marked the new VBoxVmService-6.1-Kiwi.exe as malicious. That's a big problem because McAffe and Microsoft are two of them.

Please have a look at:
https://www.virustotal.com/gui/file/ef181054002a4f11b07fe640f0da572534c5d2b6c91896f4f688965b4bb0c0d9/details

Maybe rebuilding and signing helps

**Comment by onlyfang** [comment]
Thanks @home-mp. The malicious report seems to be related to InnoSetup used to create the setup. From my point of view the package I posted to release page is pretty safe as:
* I trust InnoSetup
* I don't see any malicious issue reported on my Windows 10 machine with Virus & threat protection on.

I have no plan to purchase code signing certificate to sign the package, just to satisfy all the online scanning engines. 5 out of 71 score looks good enough to me. 

With that said, this is an open source software, people can always rebuild the software on their own, and suggestions/PRs on improving this are always welcome.

**Comment by daMark-de** [comment]
I have a similar problem. GData detect a virus in Kiwi. Download and execution is blocked. Earlier versions of VBoxVmService are ok but not compatible with VirtualBox 6.1
Is there something like a preview version of the next release of VBoxVmService? I'd like to see if GData would accept this.
