### ISSUE TITLE
After upgrade VMs not found

### ISSUE THREAD

**Issue by vasyugan** [onlyfang/VBoxVmService#38]
I have upgraded both VirtualBox  and VBoxVmService  to the latest versions (6.0.16 and 6.1 respectively). After that I notice that the service no longer finds the VMs, the log file says:

This is what I see in the logfile:

```
01/18/2020, 14:54:56 - VBoxVmService started.
01/18/2020, 14:54:56 - List all the VMs found by VBoxVmService
01/18/2020, 15:09:19 - C:\Program Files\vms\VBoxVmService64.exe
01/18/2020, 15:09:19 - C:\Program Files\vms\VBoxVmService.ini
01/18/2020, 15:09:19 - C:\Program Files\vms\VBoxVmService.log
01/18/2020, 15:09:19 - VBoxVmService started.
01/18/2020, 15:09:28 - Received service shutdown event.
01/18/2020, 15:09:30 - List all the VMs found by VBoxVmService
01/18/2020, 15:09:32 - C:\Program Files\vms\VBoxVmService64.exe
01/18/2020, 15:09:32 - C:\Program Files\vms\VBoxVmService.ini
01/18/2020, 15:09:32 - C:\Program Files\vms\VBoxVmService.log
01/18/2020, 15:09:32 - VBoxVmService started.
01/18/2020, 15:09:32 - List all the VMs found by VBoxVmService
```

I also notice that the tray service control icon no longer comes up, although the service itself seems to be running in the background.

**Comment by vasyugan** [comment]
Now uninstalled and installed 6.0 instead of 6.1,  which works, for whatever reason.

**Comment by Sanek200** [comment]
Faced the same problem:
VBoxVmService.ini

> [Settings]
VBOX_USER_HOME=C:\Users\MHG\.VirtualBox
RunWebService=no
PauseShutdown=15000
[Vm0]
VmName=Radio
ShutdownMethod=savestate
AutoStart=yes

VBoxVmService.log
> 01/20/2020, 20:29:28 - C:\vms\VBoxVmService64.exe
01/20/2020, 20:29:28 - C:\vms\VBoxVmService.ini
01/20/2020, 20:29:28 - C:\vms\VBoxVmService.log
01/20/2020, 20:29:28 - VBoxVmService started.
01/20/2020, 20:29:28 - List all the VMs found by VBoxVmService

Podskazhite kak byt'?

**Comment by vasyugan** [comment]
Have you tried 6.0 instead?

**Comment by Sanek200** [comment]
Yes, on 6.0 the log does not write

**Comment by onlyfang** [comment]
Please read the wiki https://github.com/onlyfang/VBoxVmService/wiki, VBoxVmService version needs to match with VirtualBox.
