### ISSUE TITLE
VBoxVMService starts and stops unexpectedly

### ISSUE THREAD

**Issue by get-itips** [onlyfang/VBoxVmService#39]
VBoxVmService Version: 6.1-Kiwi
VirtualBox 6.0.16

My .ini file
```[Settings]
VBOX_USER_HOME=C:\Users\administrator\.VirtualBox
RunWebService=no
PauseShutdown=5000

[Vm0]
VmName=UbuntuSrv02x86
ShutdownMethod=acpipowerbutton
AutoStart=yes
```

Running the VBoxVMService produces this log

> 01/25/2020, 09:40:14 - C:\install\vms\VBoxVmService64.exe
> 01/25/2020, 09:40:14 - C:\install\vms\VBoxVmService.ini
> 01/25/2020, 09:40:14 - C:\install\vms\VBoxVmService.log
> 01/25/2020, 09:40:14 - VBoxVmService started.
> 01/25/2020, 09:40:14 - List all the VMs found by VBoxVmService

But the VBoxVMService stops unexpectedly, with no error on screen or log file.

Also:

```C:\Install\vms>VmServiceControl.exe -l
Failed to send command to service.
Connect to pipe failed: System cannot find the file specified

Is VBoxVmService running?
```

Maybe kiwi is not ready with 6.0.16?

I appreciate, thank you

**Comment by onlyfang** [comment]
Please read the wiki https://github.com/onlyfang/VBoxVmService/wiki, VBoxVmService version needs to match with VirtualBox.
