### ISSUE TITLE
Website (suggestion): Link still redirects to sourceforge

### ISSUE THREAD

**Issue by Maxedome** [onlyfang/VBoxVmService#40]
Please update your website, so you're downloading the latest release from github and not a very old build from sourceforge. I think it would make sense to replace the sourceforge redirect link on your webpage completly with the github link.

btw; Thanks for the work on this project.

**Comment by onlyfang** [comment]
Thanks! Just asked removal of the old project from sourceforge.

**Comment by onlyfang** [comment]
Sourceforge project has been removed.
