### ISSUE TITLE
VBoxVmService

### ISSUE THREAD

**Issue by yoni3210** [onlyfang/VBoxVmService#41]
01/30/2020, 21:28:57 - VBoxVmService started.
01/30/2020, 21:28:58 - Error creating VirtualBox instance! rc = 0x80004002
01/30/2020, 21:28:58 - VBoxVmService stopped.

i'm running virtualbox version : 6.0.16 r35674

This i my configuration : 

[Settings]
VBOX_USER_HOME=C:\Users\yoni\.VirtualBox
RunWebService=no
PauseShutdown=5000

[Vm0]
VmName=Hass.io
ShutdownMethod=acpipowerbutton
AutoStart=yes

**Comment by onlyfang** [comment]
Please read the wiki https://github.com/onlyfang/VBoxVmService/wiki, VBoxVmService version needs to match with VirtualBox.
