### ISSUE TITLE
McAfee blocks 6.1 Kiwi release

### ISSUE THREAD

**Issue by briemla** [onlyfang/VBoxVmService#42]
I downloaded the 6.1 Kiwi release from the releases section. As soon as the file is downloaded, McAfee removes it saying it is a trojan called Artemis!D74580FD8306. I assume it is a false positive, but I am not allowed to deactivate McAfee and install it in my company.

I fall back to version 6.0 and Pumpkin, which works without any issues. 

Could you help to solve the issue regarding McAfee?

Kind regards
Lars

**Comment by onlyfang** [comment]
I believe this is false positive, probably related to InnoSetup used to create the setup.  Maybe you can install Visual Studio Community 2019 and build the package on your own.
