### ISSUE TITLE
"path\to\VBoxVmService-master\build\Release\VBoxVmService.exe" does not exist

### ISSUE THREAD

**Issue by avoloshin91** [onlyfang/VBoxVmService#44]
I downloaded the 6.1 version of VBoxVmService and am running Oracle Virtual Box version 6.1.4.
When I run the setup.iss script as part of step 1 via Inno Setup Compiler, it gives me an error:

> Line 35:
> Source file
> "path\to\VBoxVmService-master\build\Release\VBoxVmService.exe" does not exist

Indeed when I check that path, that .exe file is not there. I have made no modifications post unzipping the contents to my desktop, seems that .exe just isn't part of original files.

**Comment by onlyfang** [comment]
setup.iss is only required if you want to build form source. And to build from source you are supposed to run do_build.bat.
