### ISSUE TITLE
VmServiceControl icon in the taskbar

### ISSUE THREAD

**Issue by firelook** [onlyfang/VBoxVmService#45]
Hi,
since few days the VmServiceControl.exe icon doesn't want to be launch / going to the taskbar
is their a way to have a little program, as this one which can be launch manually when this one doesn't want to work on windows 10 ?

thanks in advance

**Comment by mariusebastian** [comment]
@firelook Check your antivirus, on my system the file tests positive for a trojan and is automatically removed.

**Comment by firelook** [comment]
=> done for antrivirus
somtething is wired, I reinstall and it is launch when the setup finished but doesn't put it automatically in the "automatically run tools" => I have to put it mannualy
but it is ok
