### ISSUE TITLE
Infected with Trojan?

### ISSUE THREAD

**Issue by rkleivel** [onlyfang/VBoxVmService#46]
I was about to install the VBoxVmService-6.1-Kiwi.exe, but as the cautious guy I am I did a Virus scan with Windows Defender. It reports a Trojan:Win32/Zpevdo.A on this file.
Any comment on this? False positive? 
![trojan](https://user-images.githubusercontent.com/15140187/79450678-7f684680-7fe5-11ea-935f-4a0b6780e8ba.png)
I see there is another issue "McAfee blocks 6.1 Kiwi release #42" that might be related, but with a different trojan...

**Comment by onlyfang** [comment]
This should be a false positive, most likely because InnoSetup is used to create the setup program. 
I am closing this for now, unless there are further proof that shows a real threat.
