### ISSUE TITLE
Installer recognized as Trojan

### ISSUE THREAD

**Issue by gimmi** [onlyfang/VBoxVmService#48]
Hi,

when I try to download `VBoxVmService-6.1-Kiwi.exe` from the release page, both Windows Defender and my corporate proxy reveal it as Trojan.

![image](https://user-images.githubusercontent.com/6589/82409494-32f1aa00-9a6e-11ea-88ab-5c29bbe50708.png)

Are you aware of this? This makes the tool basically unusable.

**Comment by onlyfang** [comment]
Yes, I am aware of this issue. Unfortunatelly the setup was reported as Trojan by some AntiVirus software. I've submited the setup file for malware alanyze to https://www.microsoft.com/en-us/wdsi/filesubmission/. Before the warning can be cleared by Windows Defender, you are suggested to compile the executable by your own.

**Comment by gimmi** [comment]
Thanks for quick response.

I've too asked to whitelist that file in our antivirus/proxy product, let's see.

Is it possible to also release binary as zip file? Doing a manual installation is totally feasible and should avoid this issue.

**Comment by onlyfang** [comment]
Looks like Microsoft has processed my request and removed the detection. Can you please check if the problem remains on your side?

[Submission details](https://user-images.githubusercontent.com/2869279/82567268-b8c93e80-9baf-11ea-9729-6d4eda1f9c32.png)

**Comment by gimmi** [comment]
Confirm that this morning `VBoxVmService-6.1-Kiwi.exe` is no more recognized as trojan by windows defender.

Thanks.

**Comment by onlyfang** [comment]
That's great, thanks @gimmi.
