### ISSUE TITLE
Virtualbox 6

### ISSUE THREAD

**Issue by sauloal** [onlyfang/VBoxVmService#5]
Hello,

Very nice tool. Thanks for that.

There's a new version of VB on the block.

Can the 5.2 be used with 6.0?

Will a version compatible to 6.0 be released?

**Comment by onlyfang** [comment]
I've just released version 6.0 to support VirtualBox 6.0.

**Comment by sauloal** [comment]
Fantastic. Thank for the fast response!

**Comment by Girimana** [comment]
> realized that I have not updated VBox yet. now it's running. thanks again

What have you done please to update VBox?

**Comment by sauloal** [comment]
@Girimana 

You install the new version of Virtual Box and the matching version of VBoxVmService

**Comment by Girimana** [comment]
Oh my bad, I did not. How do you check that?

> @Girimana
> 
> You install the new version of Virtual Box and the matching version of VBoxVmService

**Comment by Girimana** [comment]
Oh i have seen that currently i have oracle VM virtualbox 6.1.40. and my vboxvmservice 5.0-litchi

**Comment by Girimana** [comment]
Oh thanks a lot dear @sauloal  you have so much saved my time. Right now it's working very well. Thank you
