### ISSUE TITLE
If service starts before networking is fully started, the VMs have no network connectivity

### ISSUE THREAD

**Issue by paquettej** [onlyfang/VBoxVmService#54]
![image](https://user-images.githubusercontent.com/22698/124145960-489c1600-da5b-11eb-8781-d3c0e86a121b.png)
The network established connection soon after booting
 
![image](https://user-images.githubusercontent.com/22698/124146122-741f0080-da5b-11eb-8fa5-d5f4c2c399de.png)

 
Virtualbox started at:
00:00:00.027990 main Log opened 2021-06-30T*17:00:38.*316376700Z (1pm EDT)
 
I stopped and restarted just our scpedgevm using
 
```
c:\vms>VMServiceControl.exe -sd 0 VM0: scpedge has been shutted down. 
c:\vms>VMServiceControl.exe -l 
VM0: scpedge is running. 
c:\vms>VMServiceControl.exe -l 
VM0: scpedge is powered off. 
c:\vms>VMServiceControl.exe -su 0 
VM0: scpedge has been started up.
```
 

After a short interval, the vm was able to connect to it's external service (AWS)

Setting the service to delayed start might fix this issue, or setting another service dependency (LanManServer?)

**Comment by usjpaq** [comment]
Adding a dependency on LanmanServer seems to fix it.
