### ISSUE TITLE
Compiling VMS

### ISSUE THREAD

**Issue by aralfer** [onlyfang/VBoxVmService#6]
Hey there, congratz on VMS. It has become an essential tool for us sysadmins, developers and so who crave for this to be included directly in Vbox.

I had a really bad experience when trying to compile. I had to download 3 different VS installers, the Windows SDK and other stuff. Failed. The compile script seems to be deluxe but the required components might not be installed in any PC.

Could yo please upload the installer or binaries already compiled ?

Best regards and congratz again; great piece of software.

**Comment by onlyfang** [comment]
The setup package can be downloaded from https://github.com/onlyfang/VBoxVmService/releases.
