### ISSUE TITLE
Path correct head sore

### ISSUE THREAD

**Issue by privacyguy123** [onlyfang/VBoxVmService#65]
Your program can't find my virtual machine named "DietPi" ...

![image](https://user-images.githubusercontent.com/50337995/160108585-fc4d4695-910c-48d9-842a-32bf626a3952.png)

**Comment by Tki2000** [comment]
Please, ensure that the user account you are using to start VBoxVMService is the same that the VirtualBox is running under. They do not have to be the same as default, and as a result they will have different directories to search for VMs.
Look at Services -> VBoxVMService -> Start Session as, and configure the right user and password to start VBoxVMService.

**Comment by onlyfang** [comment]
Hope this has been addressed by @Tki2000's answer.
