### ISSUE TITLE
Service will not start after upgrading VirtualBox to 7.0

### ISSUE THREAD

**Issue by Disco2000** [onlyfang/VBoxVmService#69]
After upgrading to VirtualBox 7.0, VBoxVmService will not start. Message within the "services" reads "The VBoxVmService service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs."

**Comment by onlyfang** [comment]
Fixed in https://github.com/onlyfang/VBoxVmService/releases/tag/7.0-Persimmon.
