### ISSUE TITLE
error in compiling

### ISSUE THREAD

**Issue by firelook** [onlyfang/VBoxVmService#7]
I do not see V6 under 
https://sourceforge.net/projects/vboxvmservice/files/vboxvmservice/

so I tryed to recompile

`
1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: RelWithDebInfo x64 ------
1>Checking Build System
1>CMake does not need to re-run because D:/users_sys/git/VBoxVmService/bin/CMakeFiles/generate.stamp is up-to-date.
2>------ Rebuild All started: Project: util, Configuration: RelWithDebInfo x64 ------
2>Building Custom Rule D:/users_sys/git/VBoxVmService/CMakeLists.txt
2>CMake does not need to re-run because D:/users_sys/git/VBoxVmService/bin/CMakeFiles/generate.stamp is up-to-date.
2>Util.cpp
2>util.vcxproj -> D:\users_sys\git\VBoxVmService\bin\RelWithDebInfo\util.lib
3>------ Rebuild All started: Project: VBoxVmService, Configuration: RelWithDebInfo x64 ------
4>------ Rebuild All started: Project: VmServiceControl, Configuration: RelWithDebInfo x64 ------
5>------ Rebuild All started: Project: VmServiceTray, Configuration: RelWithDebInfo x64 ------
3>VBoxVmPipeManager.cpp
4>VmServiceControl.cpp
5>VmServiceTray.cpp
3>VBoxVmService.cpp
5>d:\users_sys\git\vboxvmservice\src\vmservicetray.cpp(304): warning C4311: 'type cast': pointer truncation from 'HMENU' to 'UINT'
5>d:\users_sys\git\vboxvmservice\src\vmservicetray.cpp(304): warning C4302: 'type cast': truncation from 'HMENU' to 'UINT'
3>Generating Code...
5>MSVCRT.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
5>D:\users_sys\git\VBoxVmService\bin\RelWithDebInfo\VmServiceTray.exe : fatal error LNK1120: 1 unresolved externals
3>VirtualBox_i.c
5>Done building project "VmServiceTray.vcxproj" -- FAILED.
4>VmServiceControl.vcxproj -> D:\users_sys\git\VBoxVmService\bin\RelWithDebInfo\VmServiceControl.exe
3>VBoxVmService.vcxproj -> D:\users_sys\git\VBoxVmService\bin\RelWithDebInfo\VBoxVmService.exe
6>------ Skipped Rebuild All: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------
6>Project not selected to build for this solution configuration 
========== Rebuild All: 4 succeeded, 1 failed, 1 skipped ==========
`
I have these errors
any suggestions please ?

**Comment by onlyfang** [comment]
The software is no longer updated at SourceForge. You can download from: https://github.com/onlyfang/VBoxVmService/releases.

To compile, just run `do_build.bat`. You'll need Visual Studio 2013 for now. Patches for other Visual Studio versions are welcome.
