### ISSUE TITLE
Error 1075: The dependency service does not exist or has been marked for deletion

### ISSUE THREAD

**Issue by frontporchguy** [onlyfang/VBoxVmService#71]
I was getting this error when starting Version 7.0 Persimmon on Windows 10 Pro desktop machine.
I dug around and finally found what I think is the problem. regedit  key
      HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\VBoxVmService
shows VBoxVmService depends on "LanmanServer,LanmanWorkstation ComSysApp" (note the missing comma).  I changed the registry to "LanmanServer, LanmanWorkstation, ComSysApp", rebooted, and the service started working. 
(I don't have a compiler on my system so while working this problem I installed the Microsoft Studio C++ redistribution libraries, but I don't think that is a factor in the solution).

**Comment by coccobill1** [comment]
Getting the same error after upgrading to 7.0. I believe the correct syntax for REG_MULTI_SZ is line breaks, not commas, as in all three should be on their separate lines. However, fixing that I get an error 1067 after a reboot and the service fails to start. Just for kicks also installed the latest vc_redist, no help.

**Comment by TimDowker** [comment]
I was able to get it working by putting each entry on it's own line.  It gave an error when closing/saving but I just clicked ok, rebooted, and it worked.

**Comment by onlyfang** [comment]
This is indeed a bug introduced in an earlier PR. Fixed at https://github.com/onlyfang/VBoxVmService/commit/ec6c408897c01ac9e2f4aec56401e4591e486776. 
I've also updated package at https://github.com/onlyfang/VBoxVmService/releases/tag/7.0-Persimmon.
