### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by kenhagin** [onlyfang/VBoxVmService#74]
Please clarify in your documentation that VirtualBox 7 is required for VBoxVmService 7 to work!  I spent several hours trying to get it to run AHEAD of upgrading VirtualBox from 6.x to 7.x.  I finally found a UUID in the source code that was not present on my system, but I was able to find the UUID on another system that had VirtualBox 7, and realized VBoxVmService 7 is NOT backwards compatible.  :-)

**Comment by onlyfang** [comment]
Updated in [wiki](https://github.com/onlyfang/VBoxVmService/wiki).
