### ISSUE TITLE
VM's not starting after Windows 11 Build 26100.712 update?!

### ISSUE THREAD

**Issue by pchenriques** [onlyfang/VBoxVmService#79]
Probably related to the Windows 11 Build 26100.712 update, since the problem started at the same time, but the VBoxVmService is not starting the VMs, neither automatically nor manually, although the VM's startup is recorded in the log. The service can, however, stop VMs manually. The status of the VM's is read correctly. Is anyone facing the same problem?

Log:
05/30/2024, 16:48:00 - Received control command: list
05/30/2024, 16:48:00 - List all the VMs found by VBoxVmService
05/30/2024, 16:48:00 -   VM0: HOMnasSY0 is powered off.
05/30/2024, 16:48:00 -   VM1: HOMnasSY3 is saved.
05/30/2024, 16:48:00 -   VM2: HOMnasSY4 is powered off.
05/30/2024, 16:48:00 -   VM3: Ubuntu server is powered off.
05/30/2024, 16:48:03 - Received control command: start 0
05/30/2024, 16:48:03 -   VM HOMnasSY0 has been started up.

**Comment by pchenriques** [comment]
It's working again, after installing AMD drivers !?

**Comment by onlyfang** [comment]
Not sure what's the root cause, but glad to know it works for you anyway.
