### ISSUE TITLE
 Please add support for virtualbox 7.1

### ISSUE THREAD

**Issue by estebandido81** [onlyfang/VBoxVmService#80]

**Comment by Wolfpaxx** [comment]
Since installation of 7.1:
09/15/2024, 20:49:22 - VBoxVmService started.
09/15/2024, 20:49:22 - Error creating VirtualBoxClient instance! rc = 0x80040154
09/15/2024, 20:49:22 - VBoxVmService stopped.

Thank you for your work, @onlyfang !

**Comment by onlyfang** [comment]
Here it comes: https://github.com/onlyfang/VBoxVmService/releases/tag/7.1-Pitaya
